name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 2 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          ref: 'web'
          path: my

      - name: Check update
        working-directory: my
        run: |
          LATEST_SHA=$(curl -s https://api.github.com/repos/zarfadev/MobaXterm-Keygen/commits/main | jq -r .sha)
          CURRENT_SHA=""
          if [ -f sha ]; then
            CURRENT_SHA=$(cat sha)
          fi

          if [ "$LATEST_SHA" = "$CURRENT_SHA" ]; then
            echo "already up to date ($LATEST_SHA)."
            echo "SHOULD_BUILD=false" >> "$GITHUB_ENV"
          else
            echo "BUILD_SHA=$LATEST_SHA" >> "$GITHUB_ENV"
            echo "SHOULD_BUILD=true" >> "$GITHUB_ENV"
          fi

      - name: Checkout target
        if: ${{ env.SHOULD_BUILD == 'true' }}
        uses: actions/checkout@v4
        with:
          repository: zarfadev/MobaXterm-Keygen
          ref: 'main'
          path: target

      - name: Copy file
        if: ${{ env.SHOULD_BUILD == 'true' }}
        working-directory: target
        run: |
          echo "$BUILD_SHA" > sha
          mkdir .public
          cp -r ./* .public/

      - name: Deploy
        if: ${{ env.SHOULD_BUILD == 'true' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: web
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/.public
